@startuml

' tables
!include tables/Product.puml
!include tables/Category.puml
!include tables/CategoryProduct.puml

Category -right- "1..*" CategoryProduct
CategoryProduct -right- "*..1" Product

@enduml